create table public.dashboard_notes (
  id bigint generated by default as identity primary key,
  content text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.dashboard_parking (
  id bigint generated by default as identity primary key,
  location_text text not null,
  latitude double precision,
  longitude double precision,
  updated_at timestamptz not null default now()
);

-- This uniquely named function avoids changing any trigger function used by existing tables.
create function public.dashboard_set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger dashboard_notes_set_updated_at before update on public.dashboard_notes for each row execute function public.dashboard_set_updated_at();
create trigger dashboard_parking_set_updated_at before update on public.dashboard_parking for each row execute function public.dashboard_set_updated_at();

alter table public.dashboard_notes enable row level security;
alter table public.dashboard_parking enable row level security;

revoke all on table public.dashboard_notes from anon, authenticated;
revoke all on table public.dashboard_parking from anon, authenticated;
revoke all on sequence public.dashboard_notes_id_seq from anon, authenticated;
revoke all on sequence public.dashboard_parking_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.dashboard_notes to authenticated;
grant select, insert, update, delete on table public.dashboard_parking to authenticated;
grant usage, select on sequence public.dashboard_notes_id_seq to authenticated;
grant usage, select on sequence public.dashboard_parking_id_seq to authenticated;

create policy "Authenticated users can select dashboard notes" on public.dashboard_notes for select to authenticated using (true);
create policy "Authenticated users can insert dashboard notes" on public.dashboard_notes for insert to authenticated with check (true);
create policy "Authenticated users can update dashboard notes" on public.dashboard_notes for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete dashboard notes" on public.dashboard_notes for delete to authenticated using (true);
create policy "Authenticated users can select dashboard parking" on public.dashboard_parking for select to authenticated using (true);
create policy "Authenticated users can insert dashboard parking" on public.dashboard_parking for insert to authenticated with check (true);
create policy "Authenticated users can update dashboard parking" on public.dashboard_parking for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete dashboard parking" on public.dashboard_parking for delete to authenticated using (true);
